# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cocktail-DB-HCM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocktail-DB-HCM
	pod 'RxSwift', '6.2.0'
	pod 'RxCocoa', '6.2.0'
	pod 'Alamofire', '~> 5.4'
	pod 'ObjectMapper', '~> 3.5'
	pod 'SDWebImage', '~> 5.0'
	pod 'Reusable'
	pod 'SnapKit', '~> 5.0.0'
	pod 'Then'
	pod 'NSObject+Rx'
	pod 'RxDataSources', '~> 5.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
      config.build_settings[“EXCLUDED_ARCHS[sdk=iphonesimulator*]“] = “arm64”
     end
    end
   end
end
